# Workflow to build and publish aide-svrtk MAP on GHCR

name: Build and package MAP

on:
  push:
    branches: ['11-gha-build']

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
#        pip install -r app/app_requirements.txt

    - name: Display installed pip packages
      run: |
        pip list

    - name: Free disk space
      run: |
        df -h
        sudo swapoff -a
        sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Package MAP & test MAP end-to-end
      run: |
        monai-deploy package app -t map-init:temp -r requirements.txt -l DEBUG
        docker images
        docker build --build-arg INIT_CONTAINER=map-init:temp -t map-final:temp app
        docker images
        